### PR TITLE
Added typings so the project can be used within Typescript

### PR DESCRIPTION
**Pull request by germanamz**
We only added typescript as a develop dependency and created the `logic.d.ts` on which the declarations for typescript are made.

### CODE REVIEW

**Comment by ankithkonda** [comment]
👍 this should really be merged in

**Comment by alfechner** [comment]
Any reason why this not merged?

The PR is open since 1/18. I evaluate this library for a new project and am kind of afraid that it's not maintained anymore.

**Comment by germanamz** [comment]
As @jwadhams has never responded to any of the comments neither the PR has been reviewed nor merged, I'm closing this PR.

**Comment by zachary95** [comment]
That's sad ... Why not uploading these typing definitions to https://github.com/DefinitelyTyped/DefinitelyTyped?

**Pull request closed without merging**
