### PR TITLE
Add installation block

### PR DESCRIPTION
**Pull request by imatveev**

### CODE REVIEW

**Comment by jwadhams** [comment]
There's already an installation block at the bottom, should we just move that up?

**Comment by imatveev** [comment]
Sorry, my mistake, missed that. Almost 100% npm packages have it on the top (reason why I missed it). If you agree that it should be moved up, I can change the PR, LMK. If no - just decline it

**Comment by jwadhams** [comment]
If it was confusing to you, it's probably confusing to lots of people who didn't put in the effort to make a PR. Let's move it up.

**Comment by imatveev** [comment]
@jwadhams Updated the PR, it can be reviewed

**Comment by jwadhams** [comment]
Thank you!

**Pull request merged**
